plotdata := ../data/LowerBound.csv
data := ../data/pion.local-local.u-gf-d-gi.px0_py0_pz0.h5
plot := ../latex/LowerBound.tex

texpath := ../latex/main.tex
pdfpath := ../latex/main.pdf
pypath := main.py
gnupath := plot.gnu

run:
	python $(pypath) $(data) $(plotdata)


